apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-ksa
      initContainers:
      - name: init
        image: google/cloud-sdk:430.0.0
        command:
        - gcloud
        - storage
        - cp
        - "<<INSERT YOUR GCS URI HERE>>" #EXAMPLE: "gs://brando-playground/index.html"
        - "work-dir/index.html"
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir" 
      containers:
      - image: nginx:1.23.4
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      volumes:
      - name: workdir
        emptyDir: {}
